### POST http://localhost:3000/api/usuarios/login
POST http://localhost:3000/api/usuarios/login
Content-Type: application/json

{
    "email": "rubenM@gmail.com",
    "password_hash": "ruben123"
}

### POST http://localhost:3000/api/usuarios/register
POST http://localhost:3000/api/usuarios/register
Content-Type: application/json

{
    "nombre": "RubenM",
    "email": "rubenM@gmail.com",
    "password_hash": "ruben123"
}